import type { Profile } from '../core/types.js';

const safeOpenCodeVersionPattern = /^(latest|\d+\.\d+\.\d+)$/;

export function generateDockerfile(profile: Profile): string {
  if (!safeOpenCodeVersionPattern.test(profile.opencodeVersion)) {
    throw new Error('Invalid opencodeVersion. Expected "latest" or a semver version like "1.2.3".');
  }

  return `# Generated by CodeCapsule - DO NOT EDIT MANUALLY
# Pin OPENCODE_VERSION for reproducible builds instead of relying on latest.
# User auth, tokens, and config are mounted at runtime; they are never baked into this image.
FROM node:22-bookworm-slim

ARG OPENCODE_VERSION=${profile.opencodeVersion}
ARG USER_ID=10001
ARG GROUP_ID=10001

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    bash \
    tini \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -g \${GROUP_ID} codecapsule \
    && useradd -u \${USER_ID} -g \${GROUP_ID} -m -d /home/codecapsule -s /bin/bash codecapsule \
    && mkdir -p /home/codecapsule/.config/opencode \
        /home/codecapsule/.local/share/opencode \
        /home/codecapsule/.cache/opencode \
    && chown -R codecapsule:codecapsule /home/codecapsule

RUN npm install -g opencode-ai@\${OPENCODE_VERSION}

ENV HOME=/home/codecapsule \
    XDG_CONFIG_HOME=/home/codecapsule/.config \
    XDG_DATA_HOME=/home/codecapsule/.local/share \
    XDG_CACHE_HOME=/home/codecapsule/.cache

USER codecapsule
WORKDIR /workspace

ENTRYPOINT ["tini", "--"]
CMD ["opencode"]
`;
}
